# This is a config for E2B sandbox template.
# You can use template ID (tqnve8xjy810a4gocbak) or template name (gen-web-ds-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("gen-web-ds-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("gen-web-ds-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('gen-web-ds-test-2')

team_id = "c87e3934-a591-41bd-a7ba-60cf56f9945d"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "gen-web-ds-test-2"
template_id = "tqnve8xjy810a4gocbak"
